[package]
name = "step_3"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion = "0.4.0"
sdl2 = "0.34.2"
assets_manager = "0.5.0"